### ISSUE TITLE
How to configure

### ISSUE THREAD

**Issue by jorisw** [atanasster/babel-plugin-theme-ui#8]
In the README, it states:

> You can configure the plugin in your webpack configuration as a babel-loader plugin

How does one do this?

**Comment by jorisw** [comment]
Because after the Configuration heading, the README continues to talk about options rather than loading the plug-in, I didn't see that below, examples are given of how the plug-in can be added to various types of projects.

Would suggest refering to those examples before talking about configuration options.

**Comment by atanasster** [comment]
Thanks, I added a link to an examples section, does this make it clearer?

**Comment by jorisw** [comment]
Perfect, thanks.
